### ISSUE TITLE
[서비스 이름 제안] 안녕하세요

### ISSUE THREAD

**Issue by Ssuamje** [bok000111/42hackathon#1]
선생님들 서비스 이름 뭘로 하셨는지 모르겠는데 몇개 추천해봅니다.
일단은 듣자마자 꽂혀야 되고 귀여우면 좋을 것 같아요
그리고 서비스 색깔도 담아야하니까 한 세개정도 생각났습니다

1. 티토(멘티, 멘토)
2. 토티(멘토, 멘티 - 근데 축구선수 생각남)
3. 멘멘(멘티, 멘토)

이정도 생각났습니다. 티토라고하면 나중에 브랜딩할 때 캐릭터 이름으로도 괜찮을 것 같네요 적극 반영 부탁드립니다

**Comment by oyhoyhk** [comment]
42PM입니다 일단은 42PeerMatching

**Comment by Ssuamje** [comment]
일단은 멘토-멘티 매칭인데 추후에 동료-동료도 염두에 두신 건가요?
피어 흡수..?
